### ISSUE TITLE
Allow greater acceleration values

### ISSUE THREAD

**Issue by owosoup** [AndyFilter/YeetMouse#10]
I use a very high DPI mouse (25600) and it requires a very low sensitivity to cram that resolution into a reasonable movement. It's a bit much to ask, but I'm struggling to replicate my Rawaccel acceleration feel, it had 0.01 sensitivity and a lot of acceleration. On your program though, the acceleration is capped:( so I can't set the sensitivity super low to get easy microadjustments at low speeds. Is there a way I can force it to use a higher acceleration for the curve I'm working with?

**Comment by AndyFilter** [comment]
Hey, You should be able to just Ctrl+LeftClick the input area, and type any number you desire. Like so: 
![YeetMouseManualInput](https://github.com/user-attachments/assets/c0890d97-443f-4796-aa4c-7fa9a6f7ba75)
The value might not be presented correctly, but it's there, You'll have to trust me on this one. I didn't think anyone would be inputting values smaller/greater than 10⁻³/10² to parameters other than _Acceleration_. But apparently I was wrong. I'll fix the issue with the next push that will also change some of the names of the parameters to more "_globally_" recognizable ones. Let me know if this fixed Your issue.

**Comment by owosoup** [comment]
Oh, thanks! I just love having a super high DPI (high-res mouselook!), so I use very low sensitivities.
